### ISSUE TITLE
TypeError: Cannot read property '500' of undefined

### ISSUE THREAD

**Issue by gurumark** [thebakerdev/tailwindcss-base-buttons#2]
Rebuild failed:

POSTCSS: failed to transform "css/styles.css" (text/css): TypeError: Cannot read property '500' of undefined
    at Object.setDefaultThemeColors [as theme] (/home/marom/codespace/sites/example.com/node_modules/tailwindcss-base-buttons/scripts/defaultOptions.js:45:46)
    at setColorConfig (/home/marom/codespace/sites/example.com/node_modules/tailwindcss-base-buttons/index.js:11:64)
    at module.exports (/home/marom/codespace/sites/example.com/node_modules/tailwindcss-base-buttons/index.js:44:25)
    at /home/marom/codespace/sites/example.com/node_modules/tailwindcss/lib/util/processPlugins.js:69:5
    at Array.forEach (<anonymous>)
    at _default (/home/marom/codespace/sites/example.com/node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
    at /home/marom/codespace/sites/example.com/node_modules/tailwindcss/lib/processTailwindFeatures.js:64:54
    at LazyResult.runOnRoot (/home/marom/codespace/sites/example.com/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/home/marom/codespace/sites/example.com/node_modules/postcss/lib/lazy-result.js:355:26)
    at async Promise.all (index 0)
Hugo Static Site Generator v0.80.0 linux/amd64 BuildDate: 2020-12-31T20:00:21Z

**Comment by gurumark** [comment]
I am using "tailwindcss": "^2.0.4"

**Comment by gurumark** [comment]
It will be great if you release another version. "npm install" does not include your fixes for tailwind 2. After merging the changes, the plugin started working for me.
